name: Build and deploy Svelte app to Hostpoint

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  # update:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install python dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y python3-pip
  #         pip3 install paramiko
  #         pip3 install googletrans==4.0.0-rc1
  #         pip3 install deepl

  #     - name: Save images on database
  #       run: |
  #         python3 images.py

  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-svelte-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-svelte-${{ hashFiles('**/package-lock.json') }}-

      - run: npm install

      - name: Build Svelte app
        run: npm run build

      - name: Deploy on Hostpoint
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH2 }}
          source: 'build/'
          target: 'www/lands.swiss'
          strip_components: 1
          rm: true

env:
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  SSH2: ${{ secrets.SSH2 }}
  DEEPL_KEY: ${{ secrets.DEEPL_KEY }}
  PASSWORD: ${{ secrets.PASSWORD }}
