name: Update the images and the navbar translations

on: 
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Install python dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y python3-pip
              pip3 install paramiko
              pip3 install googletrans==4.0.0-rc1
              pip3 install deepl

          - name: Save images on database
            run: |
              python3 images.py